### ISSUE TITLE
No 'version' key in the manifest file

### ISSUE THREAD

**Issue by mmacinko** [Verbalinsurection/next_rocket_launch#4]
No 'version' key in the manifest file for custom integration 'next_rocket_launch'. As of Home Assistant 2021.6, this integration will no longer be loaded. Please report this to the maintainer of 'next_rocket_launch'

My Home assistant is on version 2021.4.3

**Comment by Verbalinsurection** [comment]
Hi,
Information added. Thank you for your report :)
